### ISSUE TITLE
HELM Monomer Manager Issues

### ISSUE THREAD

**Issue by TianhongZhang** [PistoiaHELM/HELMWebEditor#38] opened 2016-09-26 23:21 UTC
Most of the navigation controls, page number, next page... and filtering functions are not working. Click on them causing the screen to refresh, but nothing changed. Also, saving new monomer have the same problem as saving new rule, all values are URL encoded.

**Comment by tony-yuan** [comment] 2016-09-27 13:30
This is about the Database.java file, which doesn't implement paging function yet

**Comment by tony-yuan** [comment] 2016-09-27 16:15
It turns out being a javascript issue.  Fixed now 2.0.0.2016-09-27

**Comment by TianhongZhang** [comment] 2016-09-27 23:53
The only control that works is the count, all other controls do nothing still. URL encoding issue fixed when saving new monomer.

**Comment by TianhongZhang** [comment] 2016-10-19 10:41
Symbol search is not working: try 'mK', returns nothing.
Combination filtering is not working: try Polymer Type 'CHEM' and Monomer Type 'branch'.
Deleting monomer is not working, should we allow it at all?

**Comment by ClairePA** [comment] 2016-10-20 16:28
Combination filtering is working for me, but if you try monomer type = 'undefined' you get no results. If you use monomer type = "" you get a lot of hits with no monomer type present. is this a quirk of the monomer set? Should all monomers have a specific monomer type or should 'undefined' give you all the monomers that are not 'backbone' or 'branch'. Please either fix the monomer set or the code.

**Comment by tony-yuan** [comment] 2016-10-20 17:15
Fixed in 2016-10-21 update

**Comment by ClairePA** [comment] 2017-01-30 10:29
If I define the monomer type as undefined the display updates to show the correct entries. If I then add monomer type as chem (or any other type) then the list is not updated further to take account of the second selection.

**Comment by scilligence** [comment] 2017-02-20 20:23
Fixed now

**Comment by ClairePA** [comment] 2017-02-21 10:17
confirmed fixed - close.

**Closed by ClairePA** 2017-02-21 10:17 UTC
