### ISSUE TITLE
No structure preview with inline SMILES

### ISSUE THREAD

**Issue by MarkusWeisser** [PistoiaHELM/HELMWebEditor#142] opened 2017-11-23 09:58 UTC
Using inline smiles shows a symbol #1 on the canvas. No structure is displayed on mouse over.

**Comment by scilligence** [comment] 2017-11-30 20:11
HELM Editor itself cannot parse SMILES, so it has to use web service to call server side to convert SMILES into molfile.  The *lookupurl* parameter is used for this purpose

**Comment by scilligence** [comment] 2017-11-30 20:26
var args = {
                    // ...
                    cleanupurl: "??????" // web service to clean up structures
                };

                org.helm.webeditor.Adapter.startApp("div1", args);

**Comment by ClairePA** [comment] 2017-12-01 16:00
This is not quattro's responsibility to fix. If the editor needs this function then Scilligence needs to write it. I do not mind whether it is a front or backend function but it is Scilligence's responsibility in either case.

**Comment by scilligence** [comment] 2017-12-01 20:38
HELM web editor won't be able to parse SMILES - it is huge amount to work to re-implement this using javascript.

The editor is ready to call a web service to convert SMILES into molfile.

**Comment by ClairePA** [comment] 2017-12-04 10:21
OK, thanks. I look forward to seeing your new webservice in action. I assume you will combine the changes with the HELM webservice? 

It is good to get this sorted out since the structure view is also affected. 

![image](https://user-images.githubusercontent.com/3986896/33547702-e0f71b4a-d8dc-11e7-910e-fdd7202e86c9.png)

**Comment by scilligence** [comment] 2017-12-12 15:35
Need the backend web service to convert smiles into molfile

**Comment by scilligence** [comment] 2017-12-13 19:38
Using new WAR file, and it is working now.

**Comment by ClairePA** [comment] 2017-12-14 09:49
The tool tip looks good now. 
![image](https://user-images.githubusercontent.com/3986896/33985967-0d8dea24-e0b4-11e7-9ea4-045e2b330e79.png)


However when I select the two monomer molecule to display in the structure view, I get an error. 




![image](https://user-images.githubusercontent.com/3986896/33985918-dad1ec8e-e0b3-11e7-97a1-f2955dad3075.png)

**Comment by scilligence** [comment] 2017-12-14 14:29
Fixed now

**Comment by ClairePA** [comment] 2017-12-15 10:29
It does not crash now, and does display the structures, but the monomers are not connected together. 

![image](https://user-images.githubusercontent.com/3986896/34038038-c89efe06-e182-11e7-8d52-755093e84df1.png)

**Comment by scilligence** [comment] 2017-12-15 15:39
I cannot reproduce it.  Could you upload the HELM notation you are using?

**Comment by ClairePA** [comment] 2018-01-02 16:33
PEPTIDE1{[[C@H](C(=O)*)Cc1ccc(cc1)F |$;;;_R2;;;;;;;;$|].[Hse]}$$$$V2.0

**Comment by scilligence** [comment] 2018-01-03 21:54
This is ChemAxon smiles, and I don't think CDK can read it.

**Comment by ClairePA** [comment] 2018-01-04 09:49
Something is reading it since the structure is displayed. It looks more like there is an issue with the connection points not being understood.

**Comment by scilligence** [comment] 2018-01-07 15:28
Fixed in 2018-01-08 update.  It converts the ChemAxon SMILES into CDK acceptable smiles.

**Comment by ClairePA** [comment] 2018-01-08 10:13
Now I get the following error using the HELM above:

![image](https://user-images.githubusercontent.com/3986896/34666462-70861172-f45c-11e7-8f0d-1b6b14ff2b56.png)

**Comment by scilligence** [comment] 2018-01-08 18:24
Remember to copy the HELM string in editing mode:

`PEPTIDE1{[[C@H](C(=O)*)Cc1ccc(cc1)F |$;;;_R2;;;;;;;;$|].[Hse]}$$$$V2.0`

**Comment by ClairePA** [comment] 2018-01-10 11:12
OK, looks fine.

**Closed by ClairePA** 2018-01-10 11:12 UTC
