### ISSUE TITLE
Search in monomers returns only monomer starting with search entry

### ISSUE THREAD

**Issue by ypotier** [PistoiaHELM/HELMWebEditor#124] opened 2017-10-04 16:02 UTC
If I am searching 'biotin' in the search field of the monomer manager, I am expecting to have all the Biotin from CHEM returned but I see only one returned (Biotin TEG (Glen BiotinTEG Phosphoramidite 10-1955). I also tried to use the * symbol but it did not help.

I think we fixed that issue previously but the search in the monomer manager should return all monomer matching the user entry.

**Comment by scilligence** [comment] 2017-10-13 15:42
Markus, could you check this?  This is about the server side.

**Comment by MarkusWeisser** [comment] 2017-10-17 14:00
We specified the filter criteria for searching within the symbol not the name. In addition, the search term should match the beginning of the symbol.

**Comment by ypotier** [comment] 2017-10-19 14:30
Right, this part is working, but I expect the search to behave this way in the main canvas when searching for monomers. 
However, in the monomer search, I think it is unrealistic to expect user to know the monomer symbol when searching for monomers. My example of biotin still stands: users are looking for the different biotin available and cannot find them. Is it complicated to have the search point to the monomer name AND symbol rather than just symbol?

**Comment by scilligence** [comment] 2017-10-23 15:54
Fixed in 2017-10-24 update:  if a user type a string more than 2 letters, it will filter names as well.  If just one letter or two, it will filter only symbols.

**Comment by ypotier** [comment] 2017-10-24 18:24
@MarkusWeisser , after our conversation today during the meeting. Should we assign the ticket to you or close this one and follow the enhancements independently of the editor?

**Comment by ClairePA** [comment] 2017-10-26 09:27
**_Action:_** Markus to create two backend services: one to perform a ‘contains’ search on symbol and one to perform a ‘contains’ search on name. Markus to let Tony know when this is done. 

**_Action:_** Tony to create two separate fields from the symbol/name box and call the services Markus writes.

**Comment by MarkusWeisser** [comment] 2017-10-27 14:13
New version on https://github.com/QuattroResearch/HELMMonomerService 
REST service for filtering monomers has new query parameter "filterField". Using "symbol" or "name" as query parameter will filter for these fields. If filterField is not specified, query will run for both fields (OR).

**Comment by scilligence** [comment] 2017-10-30 17:55
(1) I grabbed the new war file there, and it looks like the Name filter doesn't work.  Here is the URL I am using:

http://54.91.164.146/HELM2MonomerService/webService/service/library/monomer/ALL?limit=10&offset=0&filter=FAM&filterField=name&polymertype=&monomertype=&countperpage=

(2) If users fill both symbol and name filters, it looks like the code can do one.

**Comment by MarkusWeisser** [comment] 2017-11-02 11:53
Running the war file on a local tomcat works on my machine with this URL with MongoDB:
http://localhost:8080/HELM2MonomerService/webService/service/library/monomer/ALL?limit=10&offset=0&?monomertype=&filter=fam&filterField=name

Please check this on a local installation. Are you using MongoDB or SQLite?

**Comment by scilligence** [comment] 2017-11-13 00:17
Updated in 2017-11-13

**Comment by ClairePA** [comment] 2017-11-13 14:22
I can't get into the monomer manager at all. Clicking on the option does nothing.

**Comment by scilligence** [comment] 2017-11-13 18:20
I am not sure what URL you used.  Please start from this page: http://54.91.164.146/HELM2MonomerService/hwe/

**Comment by ypotier** [comment] 2017-11-13 20:53
I used this URL and it worked for me, thank you.

**Comment by ClairePA** [comment] 2017-11-14 10:51
Ah, I can get to the monomer manager from here:
![image](https://user-images.githubusercontent.com/3986896/32775288-ef615d5a-c926-11e7-83ea-7e9d14ec0e12.png)

but not from here:
![image](https://user-images.githubusercontent.com/3986896/32775776-51e9347e-c928-11e7-9fbd-0a7acfa9db00.png)

The functionality works perfectly.

**Comment by scilligence** [comment] 2017-11-20 20:51
It uses MongoDB now.

**Comment by ClairePA** [comment] 2017-11-21 09:38
Great, but I can't get to the monomer manager from the webeditor.

**Comment by scilligence** [comment] 2017-11-30 20:27
fixed in 2017-12-1 update

**Comment by ClairePA** [comment] 2017-12-01 16:23
Confirmed fixed. Thanks.

**Closed by ClairePA** 2017-12-01 16:23 UTC
